name: delishy
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animate_do: ^3.1.2
  bloc: ^8.1.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.4
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  http: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  ionicons: ^0.2.2
  path: ^1.8.3
  rxdart: ^0.27.7
  skeletonizer: ^0.8.0
  sqflite: ^2.3.0

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_native_splash: ^2.3.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  network_image_mock: ^2.0.1
  sqflite_common_ffi: ^2.3.0+2
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/google_fonts/

flutter_native_splash:
  color: "#ECF3F5"
  image: assets/images/man-with-shopping.png
